--- #YAML:1.0
name:               File-PatternMatch
version:            0.030
abstract:           parse media information from filenames
author:
    - Magnus Woldrich <trapd00r@trapd00r.se>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Term::ExtendedColor:  0.16
resources:
    bugtracker:  https://github.com/trapd00r/File-PatternMatch/issues
    repository:  https://github.com/trapd00r/File-PatternMatch
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
